### PR TITLE
Update schema to use string for pl:grid_cell

### PR DESCRIPTION
**Pull request by tschaub**
The `grid_cell` property (used by REOrthoTile and PSOrthoTile) is a string.  This updates the schema to reflect that.

I've also updated the remark linter config so that the `test` job passes.

### CODE REVIEW

**Comment by m-mohr** [comment]
I'm confused, the public documentation and all examples I've received say it's an integer?!

**Comment by tschaub** [comment]
@m-mohr - It sounds like we need to update some docs.  Send any links that you know of.

I know that access to this is limited, but here is the response from https://api.planet.com/data/v1/item-types/PSOrthoTile/items/6188707_5254519_2023-01-04_227c (one of the examples used in this repo):
```json
{
  "_links": {
    "_self": "https://api.planet.com/data/v1/item-types/PSOrthoTile/items/6188707_5254519_2023-01-04_227c",
    "assets": "https://api.planet.com/data/v1/item-types/PSOrthoTile/items/6188707_5254519_2023-01-04_227c/assets/",
    "thumbnail": "https://tiles.planet.com/data/v1/item-types/PSOrthoTile/items/6188707_5254519_2023-01-04_227c/thumb"
  },
  "_permissions": [
    "assets.analytic:download",
    "assets.analytic_5b:download",
    "assets.analytic_5b_xml:download",
    "assets.analytic_dn:download",
    "assets.analytic_dn_xml:download",
    "assets.analytic_sr:download",
    "assets.analytic_xml:download",
    "assets.udm:download",
    "assets.udm2:download",
    "assets.visual:download",
    "assets.visual_xml:download"
  ],
  "assets": [
    "analytic",
    "analytic_5b",
    "analytic_5b_xml",
    "analytic_dn",
    "analytic_dn_xml",
    "analytic_sr",
    "analytic_xml",
    "udm",
    "udm2",
    "visual",
    "visual_xml"
  ],
  "geometry": {
    "coordinates": [
      [
        [
          130.18019161665885,
          33.6200114123297
        ],
        [
          130.29901001213372,
          33.59921780734454
        ],
        [
          130.29901001213372,
          33.392031782604406
        ],
        [
          130.02688381435658,
          33.392031782604406
        ],
        [
          130.02688381435658,
          33.6200114123297
        ],
        [
          130.18019161665885,
          33.6200114123297
        ]
      ]
    ],
    "type": "Polygon"
  },
  "id": "6188707_5254519_2023-01-04_227c",
  "properties": {
    "acquired": "2023-01-04T01:46:56.665051Z",
    "anomalous_pixels": 0.01,
    "black_fill": 0.04,
    "clear_confidence_percent": 94,
    "clear_percent": 93,
    "cloud_cover": 0.012,
    "cloud_percent": 4,
    "columns": 8000,
    "epsg_code": 32652,
    "grid_cell": "5254519",
    "ground_control": true,
    "gsd": 4,
    "heavy_haze_percent": 0,
    "instrument": "PSB.SD",
    "item_type": "PSOrthoTile",
    "light_haze_percent": 0,
    "origin_x": 595500,
    "origin_y": 3720500,
    "pixel_resolution": 3.125,
    "provider": "planetscope",
    "published": "2023-01-04T09:10:44Z",
    "publishing_stage": "finalized",
    "quality_category": "standard",
    "rows": 8000,
    "satellite_azimuth": 100.2,
    "satellite_id": "227c",
    "shadow_percent": 2,
    "snow_ice_percent": 0,
    "strip_id": "6188707",
    "sun_azimuth": 154.7,
    "sun_elevation": 29.5,
    "updated": "2023-01-07T07:15:01Z",
    "usable_data": 0.95,
    "view_angle": 5,
    "visible_confidence_percent": 75,
    "visible_percent": 95
  },
  "type": "Feature"
}
```

And https://api.planet.com/data/v1/item-types/REOrthoTile/items/20190813_013745_5254519_RapidEye-3 (another example in the repo):
```json
{
  "_links": {
    "_self": "https://api.planet.com/data/v1/item-types/REOrthoTile/items/20190813_013745_5254519_RapidEye-3",
    "assets": "https://api.planet.com/data/v1/item-types/REOrthoTile/items/20190813_013745_5254519_RapidEye-3/assets/",
    "thumbnail": "https://tiles.planet.com/data/v1/item-types/REOrthoTile/items/20190813_013745_5254519_RapidEye-3/thumb"
  },
  "_permissions": [
    "assets.analytic:download",
    "assets.analytic_sr:download",
    "assets.analytic_xml:download",
    "assets.udm:download",
    "assets.visual:download",
    "assets.visual_xml:download"
  ],
  "assets": [
    "analytic",
    "analytic_sr",
    "analytic_xml",
    "udm",
    "visual",
    "visual_xml"
  ],
  "geometry": {
    "coordinates": [
      [
        [
          130.0295504,
          33.620011
        ],
        [
          130.2990123,
          33.6174751
        ],
        [
          130.2956483,
          33.3920412
        ],
        [
          130.0268841,
          33.3945564
        ],
        [
          130.0295504,
          33.620011
        ]
      ]
    ],
    "type": "Polygon"
  },
  "id": "20190813_013745_5254519_RapidEye-3",
  "properties": {
    "acquired": "2019-08-13T01:37:45Z",
    "anomalous_pixels": 0.09,
    "black_fill": 0,
    "catalog_id": "40352501",
    "cloud_cover": 0.09,
    "columns": 5000,
    "epsg_code": 32652,
    "grid_cell": "5254519",
    "ground_control": true,
    "gsd": 6.5,
    "item_type": "REOrthoTile",
    "origin_x": 595500,
    "origin_y": 3720500,
    "pixel_resolution": 5,
    "provider": "rapideye",
    "published": "2019-08-14T06:16:26Z",
    "rows": 5000,
    "satellite_id": "RapidEye-3",
    "strip_id": "40352462",
    "sun_azimuth": 121.08267,
    "sun_elevation": 59.57737,
    "updated": "2019-08-14T06:16:26Z",
    "usable_data": 0.91,
    "view_angle": 3.4487
  },
  "type": "Feature"
}
```

**Comment by m-mohr** [comment]
It's documented as integer at https://developers.planet.com/docs/data/reorthotile/ and https://developers.planet.com/docs/data/psorthotile/ @tschaub

**Comment by tschaub** [comment]
Thanks, @m-mohr.  I've ticketed this internally.  Any idea where the example data came from?

**Comment by m-mohr** [comment]
Mostly from Chris, but thinking more about it, I can imagine that I "fixed" the examples based on the documentation that I thought would likely be "more correct" than the examples.

**Pull request merged**
